# Generated by Django 5.0.3 on 2024-03-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_categoria_livros_usuario_livros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
