# Generated by Django 5.0.3 on 2024-03-22 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_emprestimos_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateField(default=datetime.datetime(2024, 3, 22, 16, 11, 54, 18755)),
        ),
    ]
