# Generated by Django 5.0.3 on 2024-03-27 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0022_livros_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livros'),
        ),
    ]
